name: system_bus
description: A lightweight, URI-based message broker for Dart applications.
version: 0.5.0
homepage: https://github.com/cafe01/system_bus.dart

environment:
  sdk: ^3.6.0
resolution: workspace

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  logging: ^1.1.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.16.0
