name: system_bus
description: A lightweight, URI-based message broker for Dart applications.
version: 0.2.0
homepage: https://github.com/cafe01/system_bus.dart

environment:
  sdk: '>=2.16.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  logging: ^1.1.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
