name: system_bus
description: A lightweight, URI-based message broker for Dart applications.
version: 0.1.0
homepage: https://github.com/yourusername/system_bus

environment:
  sdk: '>=2.12.0 <3.0.0'

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  logging: ^1.1.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
